Update pom.xml
This build is failing with the following error:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
```

Acording to this [link](https://github.com/jflex-de/jflex/issues/400) this is the fix and I've confirmed it compiles in CodeBuild.